export enum LanguageType {
  AFRIKAANS = "af",
  ALBANIAN = "sq",
  AMHARIC = "am",
  ARABIC = "ar",
  ARMENIAN = "hy",
  ASSAMESE = "as",
  AZERBAIJANI = "az",
  BASHKIR = "ba",
  BASQUE = "eu",
  BELARUSIAN = "be",
  BENGALI = "bn",
  BOSNIAN = "bs",
  BRETON = "br",
  BULGARIAN = "bg",
  BURMESE = "my",
  CANTONESE = "yue",
  CATALAN = "ca",
  CHINESE = "zh",
  CROATIAN = "hr",
  CZECH = "cs",
  DANISH = "da",
  DUTCH = "nl",
  ENGLISH = "en",
  ESTONIAN = "et",
  FAROESE = "fo",
  FINNISH = "fi",
  FRENCH = "fr",
  GALICIAN = "gl",
  GEORGIAN = "ka",
  GERMAN = "de",
  GREEK = "el",
  GUJARATI = "gu",
  HAITIAN_CREOLE = "ht",
  HAUSA = "ha",
  HAWAIIAN = "haw",
  HINDI = "hi",
  HUNGARIAN = "hu",
  ICELANDIC = "is",
  INDONESIAN = "id",
  ITALIAN = "it",
  JAPANESE = "ja",
  JAVANESE = "jw",
  KANNADA = "kn",
  KAZAKH = "kk",
  KHMER = "km",
  KOREAN = "ko",
  LAO = "lo",
  LATIN = "la",
  LATVIAN = "lv",
  LETZEBURGISH = "lb",
  LINGALA = "ln",
  LITHUANIAN = "lt",
  MACEDONIAN = "mk",
  MALAGASY = "mg",
  MALAY = "ms",
  MALAYALAM = "ml",
  MALTESE = "mt",
  MAORI = "mi",
  MARATHI = "mr",
  MOLDOVAN = "ro",
  MONGOLIAN = "mn",
  NEPALI = "ne",
  NORWEGIAN = "no",
  NYNORSK = "nn",
  OCCITAN = "oc",
  PANJABI = "pa",
  PASHTO = "ps",
  PERSIAN = "fa",
  POLISH = "pl",
  PORTUGUESE = "pt",
  RUSSIAN = "ru",
  SANSKRIT = "sa",
  SERBIAN = "sr",
  SHONA = "sn",
  SINDHI = "sd",
  SINHALA = "si",
  SLOVAK = "sk",
  SLOVENIAN = "sl",
  SOMALI = "so",
  SPANISH = "es",
  SUNDANESE = "su",
  SWAHILI = "sw",
  SWEDISH = "sv",
  TAGALOG = "tl",
  TAJIK = "tg",
  TAMIL = "ta",
  TATAR = "tt",
  TELUGU = "te",
  THAI = "th",
  TIBETAN = "bo",
  TURKISH = "tr",
  TURKMEN = "tk",
  HEBREW = "he",
  UKRAINIAN = "uk",
  URDU = "ur",
  UZBEK = "uz",
  VIETNAMESE = "vi",
  WELSH = "cy",
  YIDDISH = "yi",
  YORUBA = "yo",
}

export const LanguageData: Record<keyof typeof LanguageType, { code: string; flag: string }> = {
  AFRIKAANS:      { code: LanguageType.AFRIKAANS,      flag: "🇿🇦" },
  ALBANIAN:       { code: LanguageType.ALBANIAN,       flag: "🇦🇱" },
  AMHARIC:        { code: LanguageType.AMHARIC,        flag: "🇪🇹" },
  ARABIC:         { code: LanguageType.ARABIC,         flag: "🇸🇦" },
  ARMENIAN:       { code: LanguageType.ARMENIAN,       flag: "🇦🇲" },
  ASSAMESE:       { code: LanguageType.ASSAMESE,       flag: "🇮🇳" },
  AZERBAIJANI:    { code: LanguageType.AZERBAIJANI,    flag: "🇦🇿" },
  BASHKIR:        { code: LanguageType.BASHKIR,        flag: "🇷🇺" },
  BASQUE:         { code: LanguageType.BASQUE,         flag: "🇪🇸" },
  BELARUSIAN:     { code: LanguageType.BELARUSIAN,     flag: "🇧🇾" },
  BENGALI:        { code: LanguageType.BENGALI,        flag: "🇧🇩" },
  BOSNIAN:        { code: LanguageType.BOSNIAN,        flag: "🇧🇦" },
  BRETON:         { code: LanguageType.BRETON,         flag: "🇫🇷" },
  BULGARIAN:      { code: LanguageType.BULGARIAN,      flag: "🇧🇬" },
  BURMESE:        { code: LanguageType.BURMESE,        flag: "🇲🇲" },
  CANTONESE:      { code: LanguageType.CANTONESE,      flag: "🇭🇰" },
  CATALAN:        { code: LanguageType.CATALAN,        flag: "🇪🇸" },
  CHINESE:        { code: LanguageType.CHINESE,        flag: "🇨🇳" },
  CROATIAN:       { code: LanguageType.CROATIAN,       flag: "🇭🇷" },
  CZECH:          { code: LanguageType.CZECH,          flag: "🇨🇿" },
  DANISH:         { code: LanguageType.DANISH,         flag: "🇩🇰" },
  DUTCH:          { code: LanguageType.DUTCH,          flag: "🇳🇱" },
  ENGLISH:        { code: LanguageType.ENGLISH,        flag: "🇬🇧" },
  ESTONIAN:       { code: LanguageType.ESTONIAN,       flag: "🇪🇪" },
  FAROESE:        { code: LanguageType.FAROESE,        flag: "🇫🇴" },
  FINNISH:        { code: LanguageType.FINNISH,        flag: "🇫🇮" },
  FRENCH:         { code: LanguageType.FRENCH,         flag: "🇫🇷" },
  GALICIAN:       { code: LanguageType.GALICIAN,       flag: "🇪🇸" },
  GEORGIAN:       { code: LanguageType.GEORGIAN,       flag: "🇬🇪" },
  GERMAN:         { code: LanguageType.GERMAN,         flag: "🇩🇪" },
  GREEK:          { code: LanguageType.GREEK,          flag: "🇬🇷" },
  GUJARATI:       { code: LanguageType.GUJARATI,       flag: "🇮🇳" },
  HAITIAN_CREOLE: { code: LanguageType.HAITIAN_CREOLE, flag: "🇭🇹" },
  HAUSA:          { code: LanguageType.HAUSA,          flag: "🇳🇬" },
  HAWAIIAN:       { code: LanguageType.HAWAIIAN,       flag: "🇺🇸" },
  HINDI:          { code: LanguageType.HINDI,          flag: "🇮🇳" },
  HUNGARIAN:      { code: LanguageType.HUNGARIAN,      flag: "🇭🇺" },
  ICELANDIC:      { code: LanguageType.ICELANDIC,      flag: "🇮🇸" },
  INDONESIAN:     { code: LanguageType.INDONESIAN,     flag: "🇮🇩" },
  ITALIAN:        { code: LanguageType.ITALIAN,        flag: "🇮🇹" },
  JAPANESE:       { code: LanguageType.JAPANESE,       flag: "🇯🇵" },
  JAVANESE:       { code: LanguageType.JAVANESE,       flag: "🇮🇩" },
  KANNADA:        { code: LanguageType.KANNADA,        flag: "🇮🇳" },
  KAZAKH:         { code: LanguageType.KAZAKH,         flag: "🇰🇿" },
  KHMER:          { code: LanguageType.KHMER,          flag: "🇰🇭" },
  KOREAN:         { code: LanguageType.KOREAN,         flag: "🇰🇷" },
  LAO:            { code: LanguageType.LAO,            flag: "🇱🇦" },
  LATIN:          { code: LanguageType.LATIN,          flag: "🏳️" },
  LATVIAN:        { code: LanguageType.LATVIAN,        flag: "🇱🇻" },
  LETZEBURGISH:   { code: LanguageType.LETZEBURGISH,   flag: "🇱🇺" },
  LINGALA:        { code: LanguageType.LINGALA,        flag: "🇨🇩" },
  LITHUANIAN:     { code: LanguageType.LITHUANIAN,     flag: "🇱🇹" },
  MACEDONIAN:     { code: LanguageType.MACEDONIAN,     flag: "🇲🇰" },
  MALAGASY:       { code: LanguageType.MALAGASY,       flag: "🇲🇬" },
  MALAY:          { code: LanguageType.MALAY,          flag: "🇲🇾" },
  MALAYALAM:      { code: LanguageType.MALAYALAM,      flag: "🇮🇳" },
  MALTESE:        { code: LanguageType.MALTESE,        flag: "🇲🇹" },
  MAORI:          { code: LanguageType.MAORI,          flag: "🇳🇿" },
  MARATHI:        { code: LanguageType.MARATHI,        flag: "🇮🇳" },
  MOLDOVAN:       { code: LanguageType.MOLDOVAN,       flag: "🇷🇴" },
  MONGOLIAN:      { code: LanguageType.MONGOLIAN,      flag: "🇲🇳" },
  NEPALI:         { code: LanguageType.NEPALI,         flag: "🇳🇵" },
  NORWEGIAN:      { code: LanguageType.NORWEGIAN,      flag: "🇳🇴" },
  NYNORSK:        { code: LanguageType.NYNORSK,        flag: "🇳🇴" },
  OCCITAN:        { code: LanguageType.OCCITAN,        flag: "🇫🇷" },
  PANJABI:        { code: LanguageType.PANJABI,        flag: "🇮🇳" },
  PASHTO:         { code: LanguageType.PASHTO,         flag: "🇦🇫" },
  PERSIAN:        { code: LanguageType.PERSIAN,        flag: "🇮🇷" },
  POLISH:         { code: LanguageType.POLISH,         flag: "🇵🇱" },
  PORTUGUESE:     { code: LanguageType.PORTUGUESE,     flag: "🇵🇹" },
  RUSSIAN:        { code: LanguageType.RUSSIAN,        flag: "🇷🇺" },
  SANSKRIT:       { code: LanguageType.SANSKRIT,       flag: "🇮🇳" },
  SERBIAN:        { code: LanguageType.SERBIAN,        flag: "🇷🇸" },
  SHONA:          { code: LanguageType.SHONA,          flag: "🇿🇼" },
  SINDHI:         { code: LanguageType.SINDHI,         flag: "🇵🇰" },
  SINHALA:        { code: LanguageType.SINHALA,        flag: "🇱🇰" },
  SLOVAK:         { code: LanguageType.SLOVAK,         flag: "🇸🇰" },
  SLOVENIAN:      { code: LanguageType.SLOVENIAN,      flag: "🇸🇮" },
  SOMALI:         { code: LanguageType.SOMALI,         flag: "🇸🇴" },
  SPANISH:        { code: LanguageType.SPANISH,        flag: "🇪🇸" },
  SUNDANESE:      { code: LanguageType.SUNDANESE,      flag: "🇮🇩" },
  SWAHILI:        { code: LanguageType.SWAHILI,        flag: "🇰🇪" },
  SWEDISH:        { code: LanguageType.SWEDISH,        flag: "🇸🇪" },
  TAGALOG:        { code: LanguageType.TAGALOG,        flag: "🇵🇭" },
  TAJIK:          { code: LanguageType.TAJIK,          flag: "🇹🇯" },
  TAMIL:          { code: LanguageType.TAMIL,          flag: "🇮🇳" },
  TATAR:          { code: LanguageType.TATAR,          flag: "🇷🇺" },
  TELUGU:         { code: LanguageType.TELUGU,         flag: "🇮🇳" },
  THAI:           { code: LanguageType.THAI,           flag: "🇹🇭" },
  TIBETAN:        { code: LanguageType.TIBETAN,        flag: "🇨🇳" },
  TURKISH:        { code: LanguageType.TURKISH,        flag: "🇹🇷" },
  TURKMEN:        { code: LanguageType.TURKMEN,        flag: "🇹🇲" },
  HEBREW:         { code: LanguageType.HEBREW,         flag: "🇮🇱" },
  UKRAINIAN:      { code: LanguageType.UKRAINIAN,      flag: "🇺🇦" },
  URDU:           { code: LanguageType.URDU,           flag: "🇵🇰" },
  UZBEK:          { code: LanguageType.UZBEK,          flag: "🇺🇿" },
  VIETNAMESE:     { code: LanguageType.VIETNAMESE,     flag: "🇻🇳" },
  WELSH:          { code: LanguageType.WELSH,          flag: "🏴" },
  YIDDISH:        { code: LanguageType.YIDDISH,        flag: "🇮🇱" },
  YORUBA:         { code: LanguageType.YORUBA,         flag: "🇳🇬" },
};

/*Object.values(LanguageData).forEach((lang) => {
  console.log(lang.code);
});*/
