from typing import Dict

from core.brevio.enums.language import LanguageType

LANGUAGE_CHARS_PER_TOKEN: Dict[LanguageType, float] = {
    # CJK + Tailandés (alto consumo de tokens)
    LanguageType.CHINESE: 0.5,
    LanguageType.MANDARIN: 0.5,
    LanguageType.CANTONESE: 0.5,
    LanguageType.JAPANESE: 0.5,
    LanguageType.KOREAN: 0.5,
    LanguageType.THAI: 0.5,
    # Scripts complejos (3.0-3.5 caracteres/token)
    LanguageType.ARABIC: 3.2,
    LanguageType.HEBREW: 3.5,
    LanguageType.PERSIAN: 3.2,
    LanguageType.URDU: 3.2,
    LanguageType.SINDHI: 3.2,
    LanguageType.PASHTO: 3.2,
    LanguageType.PUSHTO: 3.2,
    LanguageType.TAMIL: 3.0,
    LanguageType.TELUGU: 3.0,
    LanguageType.KANNADA: 3.0,
    LanguageType.MALAYALAM: 3.0,
    LanguageType.BENGALI: 3.0,
    LanguageType.ASSAMESE: 3.0,
    LanguageType.HINDI: 3.0,
    LanguageType.MARATHI: 3.0,
    LanguageType.GUJARATI: 3.0,
    LanguageType.PANJABI: 3.0,
    LanguageType.NEPALI: 3.0,
    LanguageType.SANSKRIT: 3.0,
    LanguageType.SINHALA: 3.0,
    LanguageType.BURMESE: 3.0,
    LanguageType.MYANMAR: 3.0,
    LanguageType.KHMER: 3.0,
    LanguageType.LAO: 3.0,
    LanguageType.TIBETAN: 3.0,
    # Sudeste Asiático (híbridos)
    LanguageType.VIETNAMESE: 3.5,
    LanguageType.INDONESIAN: 4.0,
    LanguageType.JAVANESE: 4.0,
    LanguageType.SUNDANESE: 4.0,
    LanguageType.TAGALOG: 4.0,
    # Europeos (4.0 estándar)
    LanguageType.ENGLISH: 4.0,
    LanguageType.SPANISH: 4.0,
    LanguageType.FRENCH: 4.0,
    LanguageType.GERMAN: 4.0,
    LanguageType.ITALIAN: 4.0,
    LanguageType.PORTUGUESE: 4.0,
    LanguageType.DUTCH: 4.0,
    LanguageType.RUSSIAN: 4.0,
    LanguageType.UKRAINIAN: 4.0,
    LanguageType.POLISH: 4.0,
    LanguageType.CZECH: 4.0,
    LanguageType.SLOVAK: 4.0,
    LanguageType.SLOVENIAN: 4.0,
    LanguageType.CROATIAN: 4.0,
    LanguageType.BOSNIAN: 4.0,
    LanguageType.SERBIAN: 4.0,
    LanguageType.BULGARIAN: 4.0,
    LanguageType.MACEDONIAN: 4.0,
    LanguageType.BELARUSIAN: 4.0,
    LanguageType.GREEK: 4.0,
    LanguageType.ALBANIAN: 4.0,
    LanguageType.ROMANIAN: 4.0,
    LanguageType.HUNGARIAN: 4.0,
    LanguageType.FINNISH: 4.0,
    LanguageType.SWEDISH: 4.0,
    LanguageType.DANISH: 4.0,
    LanguageType.NORWEGIAN: 4.0,
    LanguageType.ICELANDIC: 4.0,
    LanguageType.FAROESE: 4.0,
    LanguageType.IRISH: 4.0,
    LanguageType.BRETON: 4.0,
    LanguageType.WELSH: 4.0,
    LanguageType.GALICIAN: 4.0,
    LanguageType.CATALAN: 4.0,
    LanguageType.BASQUE: 4.0,
    LanguageType.LATVIAN: 4.0,
    LanguageType.LITHUANIAN: 4.0,
    LanguageType.ESTONIAN: 4.0,
    LanguageType.MALTESE: 4.0,
    # Otros alfabetos no latinos
    LanguageType.ARMENIAN: 4.0,
    LanguageType.GEORGIAN: 4.0,
    LanguageType.TURKISH: 4.0,
    LanguageType.AZERBAIJANI: 4.0,
    LanguageType.TATAR: 4.0,
    LanguageType.KAZAKH: 4.0,
    LanguageType.UZBEK: 4.0,
    LanguageType.TURKMEN: 4.0,
    LanguageType.TAJIK: 4.0,
    LanguageType.MONGOLIAN: 3.5,
    # Lenguas africanas
    LanguageType.AFRIKAANS: 4.0,
    LanguageType.HAUSA: 4.0,
    LanguageType.YORUBA: 4.0,
    LanguageType.SHONA: 4.0,
    LanguageType.SWAHILI: 4.0,
    LanguageType.SOMALI: 4.0,
    LanguageType.AMHARIC: 3.5,
    LanguageType.LINGALA: 4.0,
    LanguageType.MALAGASY: 4.0,
    # Lenguas oceánicas
    LanguageType.HAWAIIAN: 4.0,
    LanguageType.MAORI: 4.0,
    # Clásicos/otros
    LanguageType.LATIN: 4.0,
    LanguageType.OCCITAN: 4.0,
    LanguageType.YIDDISH: 4.0,
    LanguageType.LETZEBURGISH: 4.0,
    LanguageType.BASHKIR: 4.0,
}
